development:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] || 'mongodb://localhost:27017/freelancing_agent_dev' %>

test:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI_TEST'] || 'mongodb://localhost:27017/freelancing_agent_test' %>

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
